name: CI Workflow

on:
  push:
    branches:
      - feature/ci-pipeline-start
  pull_request:
    branches:
      - feature/ci-pipeline-start

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    services:
      mongodb: # MongoDB service for backend tests
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test

      # Step 3: Set up Node.js for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 4: Start backend and frontend
      - name: Start backend and frontend
        run: |
          cd backend && npm start &
          cd ../frontend && npm start &
